package test;

import com.megacity.dao.CarDAOImpl;
import com.megacity.dao.daoImpl.CarDAO;
import com.megacity.model.Car;

import java.sql.SQLException;
import java.util.List;

public class CarTest {
    public static void main(String[] args) {
        CarDAO carDAO = new CarDAOImpl();

        // 1. Add a new car
        // Note: The Car constructor requires an id, name, plate number, year, price, and model.
        // The id is usually generated by the database, so you can pass 0 or another placeholder.
        Car newCar = new Car(0, "Toyota", "ABC123", 2020, 25000.00, "Corolla");
        carDAO.addCar(newCar);
        System.out.println("Car added.");

        // 2. Retrieve a car by ID
        // Adjust the id based on your database. Here, we assume id 1 exists.
        Car retrievedCar = carDAO.getCarById(1);
        System.out.println("Retrieved Car: " + retrievedCar);

        // 3. Update the car's details
        if (retrievedCar != null) {
            // For example, update the price.
            retrievedCar.setPrice(26000.00);
            carDAO.updateCar(retrievedCar);
            System.out.println("Car updated.");
        } else {
            System.out.println("No car found with id 1 to update.");
        }

        // 4. Get all cars and display them
        List<Car> cars = carDAO.getAllCars();
        System.out.println("All Cars:");
        for (Car car : cars) {
            System.out.println(car);
        }

        // 5. Delete a car by ID
        // Adjust the id to the one you want to delete. Here, we assume id 1.
        carDAO.deleteCar(1);
        System.out.println("Car deleted.");

    }
}
